SELECT FLAVOR
FROM (
        SELECT A.FLAVOR, SUM(A.TOTAL_ORDER + B.TOTAL_ORDER)
        FROM FIRST_HALF A JOIN
        (
            SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER
            FROM JULY
            GROUP BY FLAVOR
        ) B
        ON A.FLAVOR = B.FLAVOR
        GROUP BY A.FLAVOR
        ORDER BY SUM(A.TOTAL_ORDER + B.TOTAL_ORDER) DESC
    )
WHERE ROWNUM <= 3;
